# Generated by Django 5.1.3 on 2024-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_options_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='Unknown Name', max_length=100),
        ),
    ]
