# Generated by Django 5.1.3 on 2024-11-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
